VAE_PATH = "/home2/ckpts/pretrained/models/BEV_VAE_CARLA_RANDOM_BEV_CARLA_STANDARD_0.01_0.01_256_64.pt"
ENCODER_PATH = "/home2/ckpts/pretrained/models/FPV_BEV_CARLA_RANDOM_BEV_CARLA_STANDARD_0.1_0.01_128_512.pt"
LSTM_PATH = "/home2/ckpts/pretrained/carla/BEV_LSTM_CARLA_RANDOM_BEV_CARLA_STANDARD_0.1_0.01_1_512.pt"
POLICY_PATH = "/home2/carla/checkpoint"
ANCHOR_PATH = "/home/carla/img2cmd/anchor"
